#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mynfo.Droid.Resource", IsApplication=true)]

namespace Mynfo.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010002
			public const int colorAccent = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimary = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int colorPrimaryDark = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int launcher_background = 2130771973;
			
			// aapt resource value: 0x7F010000
			public const int ListViewHighlighted = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int ListViewSelected = 2130771969;
			
			// aapt resource value: 0x7F010006
			public const int splash_background = 2130771974;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020010
			public const int account = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int arroba = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int back = 2130837522;
			
			// aapt resource value: 0x7F020000
			public const int Captura = 2130837504;
			
			// aapt resource value: 0x7F020013
			public const int check = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int check3 = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int checkb = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int checkn = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int comments1 = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int compra = 2130837528;
			
			// aapt resource value: 0x7F020001
			public const int Conections = 2130837505;
			
			// aapt resource value: 0x7F020019
			public const int configuraciones = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int connections_icon = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int edit1 = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int edit2 = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int edit3 = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int enter1 = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int facebook = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int facebook1 = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int facebook2 = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int facebook3 = 2130837538;
			
			// aapt resource value: 0x7F020002
			public const int GIF_Facebook = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int GIF_Facebook2 = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int GIF_Facebook3 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int GIF_Facebook4 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int GIF_LinkedIn = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int GIF_Spotify = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int GIF_Youtube = 2130837512;
			
			// aapt resource value: 0x7F020023
			public const int gmail1 = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int gmail2 = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int gmail3 = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int home_icon = 2130837542;
			
			// aapt resource value: 0x7F02002A
			public const int icono_option = 2130837546;
			
			// aapt resource value: 0x7F020028
			public const int icon_qr = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int icon_tag = 2130837545;
			
			// aapt resource value: 0x7F020027
			public const int ic_navigation_arrow_back = 2130837543;
			
			// aapt resource value: 0x7F02002B
			public const int instagram3 = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int instagramlogo1 = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int instagramlogo2 = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int layout1 = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int layout2 = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int linkedin = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int linkedin1 = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int linkedin2 = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int linkedin3 = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int lista = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int logo = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int logo2 = 2130837558;
			
			// aapt resource value: 0x7F020009
			public const int Logo3 = 2130837513;
			
			// aapt resource value: 0x7F020037
			public const int logo4 = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int logo5 = 2130837560;
			
			// aapt resource value: 0x7F02000A
			public const int Logo6 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int Logo7 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int Logo8 = 2130837516;
			
			// aapt resource value: 0x7F02003C
			public const int logout = 2130837564;
			
			// aapt resource value: 0x7F02000D
			public const int Logo_sin_relleno = 2130837517;
			
			// aapt resource value: 0x7F020039
			public const int logo_superior = 2130837561;
			
			// aapt resource value: 0x7F02003A
			public const int logo_superior2 = 2130837562;
			
			// aapt resource value: 0x7F02003B
			public const int logo_superior3 = 2130837563;
			
			// aapt resource value: 0x7F02003D
			public const int mail1 = 2130837565;
			
			// aapt resource value: 0x7F02003E
			public const int mail2 = 2130837566;
			
			// aapt resource value: 0x7F02003F
			public const int mail3 = 2130837567;
			
			// aapt resource value: 0x7F020040
			public const int networks_icon = 2130837568;
			
			// aapt resource value: 0x7F020041
			public const int no = 2130837569;
			
			// aapt resource value: 0x7F020042
			public const int no_image = 2130837570;
			
			// aapt resource value: 0x7F020043
			public const int paleta = 2130837571;
			
			// aapt resource value: 0x7F020044
			public const int paleta2 = 2130837572;
			
			// aapt resource value: 0x7F020045
			public const int pelta3 = 2130837573;
			
			// aapt resource value: 0x7F020046
			public const int perfiles = 2130837574;
			
			// aapt resource value: 0x7F02000E
			public const int Plus = 2130837518;
			
			// aapt resource value: 0x7F020047
			public const int plusb = 2130837575;
			
			// aapt resource value: 0x7F020048
			public const int plusn = 2130837576;
			
			// aapt resource value: 0x7F020049
			public const int question = 2130837577;
			
			// aapt resource value: 0x7F02004A
			public const int question1 = 2130837578;
			
			// aapt resource value: 0x7F02004B
			public const int snapchat1 = 2130837579;
			
			// aapt resource value: 0x7F02004C
			public const int snapchat2 = 2130837580;
			
			// aapt resource value: 0x7F02004D
			public const int snapchat3 = 2130837581;
			
			// aapt resource value: 0x7F02004E
			public const int spotify = 2130837582;
			
			// aapt resource value: 0x7F02004F
			public const int spotify1 = 2130837583;
			
			// aapt resource value: 0x7F020050
			public const int spotify2 = 2130837584;
			
			// aapt resource value: 0x7F020051
			public const int spotify3 = 2130837585;
			
			// aapt resource value: 0x7F02000F
			public const int SS = 2130837519;
			
			// aapt resource value: 0x7F020052
			public const int tel1 = 2130837586;
			
			// aapt resource value: 0x7F020053
			public const int tel2 = 2130837587;
			
			// aapt resource value: 0x7F020054
			public const int tel3 = 2130837588;
			
			// aapt resource value: 0x7F020055
			public const int telegram1 = 2130837589;
			
			// aapt resource value: 0x7F020056
			public const int telegram2 = 2130837590;
			
			// aapt resource value: 0x7F020057
			public const int telegram3 = 2130837591;
			
			// aapt resource value: 0x7F020058
			public const int tiktok1 = 2130837592;
			
			// aapt resource value: 0x7F020059
			public const int tiktok2 = 2130837593;
			
			// aapt resource value: 0x7F02005A
			public const int tiktok3 = 2130837594;
			
			// aapt resource value: 0x7F02005B
			public const int time = 2130837595;
			
			// aapt resource value: 0x7F02005C
			public const int tipos = 2130837596;
			
			// aapt resource value: 0x7F02005D
			public const int trash = 2130837597;
			
			// aapt resource value: 0x7F02005E
			public const int trash1 = 2130837598;
			
			// aapt resource value: 0x7F02005F
			public const int trash2 = 2130837599;
			
			// aapt resource value: 0x7F020060
			public const int trash3 = 2130837600;
			
			// aapt resource value: 0x7F020061
			public const int twitch1 = 2130837601;
			
			// aapt resource value: 0x7F020062
			public const int twitch2 = 2130837602;
			
			// aapt resource value: 0x7F020063
			public const int twitch3 = 2130837603;
			
			// aapt resource value: 0x7F020064
			public const int twitter3 = 2130837604;
			
			// aapt resource value: 0x7F020065
			public const int twitterlogo1 = 2130837605;
			
			// aapt resource value: 0x7F020066
			public const int twitterlogo2 = 2130837606;
			
			// aapt resource value: 0x7F020067
			public const int whatsapp1 = 2130837607;
			
			// aapt resource value: 0x7F020068
			public const int whatsapp2 = 2130837608;
			
			// aapt resource value: 0x7F020069
			public const int whatsapp3 = 2130837609;
			
			// aapt resource value: 0x7F02006A
			public const int youtube = 2130837610;
			
			// aapt resource value: 0x7F02006B
			public const int youtube1 = 2130837611;
			
			// aapt resource value: 0x7F02006C
			public const int youtube2 = 2130837612;
			
			// aapt resource value: 0x7F02006D
			public const int youtube3 = 2130837613;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int launcher_foreground = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int card_title = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int service_name = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int DrawerArrowStyle = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int MainTheme = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int MyThemeDark_Splash = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int MyTheme_Splash = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int NightTheme = 2131165188;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F080000
			public const int aid_list = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int file_paths = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int nfc = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int techlist = 2131230723;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
