//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mynfo.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mynfo.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My active accounts.
        /// </summary>
        public static string ActiveAccounts {
            get {
                return ResourceManager.GetString("ActiveAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add account.
        /// </summary>
        public static string AddAccount {
            get {
                return ResourceManager.GetString("AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add network.
        /// </summary>
        public static string AddNetwork {
            get {
                return ResourceManager.GetString("AddNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add profiles to Box.
        /// </summary>
        public static string AddPBox {
            get {
                return ResourceManager.GetString("AddPBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add profiles.
        /// </summary>
        public static string AddProfiles {
            get {
                return ResourceManager.GetString("AddProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add profile to social network.
        /// </summary>
        public static string AddPSocialMedia {
            get {
                return ResourceManager.GetString("AddPSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Age:.
        /// </summary>
        public static string AgeLabel {
            get {
                return ResourceManager.GetString("AgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 21 years old.
        /// </summary>
        public static string AgePlaceHolder {
            get {
                return ResourceManager.GetString("AgePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All the Boxes that you configure and manipulate from now on will be reflected in your sticker..
        /// </summary>
        public static string AllConfigSticker {
            get {
                return ResourceManager.GetString("AllConfigSticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alpha Code 2:.
        /// </summary>
        public static string AlphaCode2 {
            get {
                return ResourceManager.GetString("AlphaCode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alpha Code 3:.
        /// </summary>
        public static string AlphaCode3 {
            get {
                return ResourceManager.GetString("AlphaCode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a and stick it to the back of your phone..
        /// </summary>
        public static string AndStick {
            get {
                return ResourceManager.GetString("AndStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  years old.
        /// </summary>
        public static string Anios {
            get {
                return ResourceManager.GetString("Anios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area:.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to delete the network permanently from the box?.
        /// </summary>
        public static string AskDeleteNetworkFromBox {
            get {
                return ResourceManager.GetString("AskDeleteNetworkFromBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borders.
        /// </summary>
        public static string Borders {
            get {
                return ResourceManager.GetString("Borders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Box list.
        /// </summary>
        public static string BoxList {
            get {
                return ResourceManager.GetString("BoxList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Box name.
        /// </summary>
        public static string BoxName {
            get {
                return ResourceManager.GetString("BoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brazilian:.
        /// </summary>
        public static string Brazilian {
            get {
                return ResourceManager.GetString("Brazilian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capital:.
        /// </summary>
        public static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password was changed successfully..
        /// </summary>
        public static string ChagePasswordConfirm {
            get {
                return ResourceManager.GetString("ChagePasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Touch the image to change it.
        /// </summary>
        public static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Networks.
        /// </summary>
        public static string ChooseTypeProfile {
            get {
                return ResourceManager.GetString("ChooseTypeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CIOC:.
        /// </summary>
        public static string CIOC {
            get {
                return ResourceManager.GetString("CIOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colorless.
        /// </summary>
        public static string Colorless {
            get {
                return ResourceManager.GetString("Colorless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Setting sticker . . . .
        /// </summary>
        public static string ConfigSticker {
            get {
                return ResourceManager.GetString("ConfigSticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sticker configurated!.
        /// </summary>
        public static string ConfigStickerRi {
            get {
                return ResourceManager.GetString("ConfigStickerRi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configure TAG.
        /// </summary>
        public static string ConfigureTAG {
            get {
                return ResourceManager.GetString("ConfigureTAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string ConfirmLabel {
            get {
                return ResourceManager.GetString("ConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the password confirm....
        /// </summary>
        public static string ConfirmPlaceHolder {
            get {
                return ResourceManager.GetString("ConfirmPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a confirm..
        /// </summary>
        public static string ConfirmValidation {
            get {
                return ResourceManager.GetString("ConfirmValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password and confirm does not match..
        /// </summary>
        public static string ConfirmValidation2 {
            get {
                return ResourceManager.GetString("ConfirmValidation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please turn on your internet settings..
        /// </summary>
        public static string ConnectionError1 {
            get {
                return ResourceManager.GetString("ConnectionError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check you internet connection..
        /// </summary>
        public static string ConnectionError2 {
            get {
                return ResourceManager.GetString("ConnectionError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create email profile.
        /// </summary>
        public static string CreateProfileEmail {
            get {
                return ResourceManager.GetString("CreateProfileEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create phone profile .
        /// </summary>
        public static string CreateProfilePhone {
            get {
                return ResourceManager.GetString("CreateProfilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Croatian:.
        /// </summary>
        public static string Croatian {
            get {
                return ResourceManager.GetString("Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your current password.
        /// </summary>
        public static string CurrentPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("CurrentPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cyan.
        /// </summary>
        public static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dark blue.
        /// </summary>
        public static string DarkBlue {
            get {
                return ResourceManager.GetString("DarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dark green.
        /// </summary>
        public static string DarkGreen {
            get {
                return ResourceManager.GetString("DarkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Box.
        /// </summary>
        public static string DefaultBox {
            get {
                return ResourceManager.GetString("DefaultBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are about to delete the box permanently, do you want to continue?.
        /// </summary>
        public static string DeleteBoxNotification {
            get {
                return ResourceManager.GetString("DeleteBoxNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demonym:.
        /// </summary>
        public static string Demonym {
            get {
                return ResourceManager.GetString("Demonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Box details.
        /// </summary>
        public static string DetailBox {
            get {
                return ResourceManager.GetString("DetailBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dutch:.
        /// </summary>
        public static string Dutch {
            get {
                return ResourceManager.GetString("Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit email profile.
        /// </summary>
        public static string EditEmail {
            get {
                return ResourceManager.GetString("EditEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit network.
        /// </summary>
        public static string EditNetwork {
            get {
                return ResourceManager.GetString("EditNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit phone profile.
        /// </summary>
        public static string EditPhone {
            get {
                return ResourceManager.GetString("EditPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit profile data.
        /// </summary>
        public static string EditProfileData {
            get {
                return ResourceManager.GetString("EditProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-Mail.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your email.
        /// </summary>
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email profile list.
        /// </summary>
        public static string EmailProfileList {
            get {
                return ResourceManager.GetString("EmailProfileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter an email.
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a valid email.
        /// </summary>
        public static string EmailValidation2 {
            get {
                return ResourceManager.GetString("EmailValidation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You do not have networks added to this box yet.
        /// </summary>
        public static string EmptyBox {
            get {
                return ResourceManager.GetString("EmptyBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has occurred, please try again later.
        /// </summary>
        public static string ErrorAddProfile {
            get {
                return ResourceManager.GetString("ErrorAddProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password can&apos;t be changed, please try latter.
        /// </summary>
        public static string ErrorChangingPassword {
            get {
                return ResourceManager.GetString("ErrorChangingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scan QR.
        /// </summary>
        public static string EscanQR {
            get {
                return ResourceManager.GetString("EscanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a example@domain.com.
        /// </summary>
        public static string ExampleEmail {
            get {
                return ResourceManager.GetString("ExampleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of Facebook profiles.
        /// </summary>
        public static string FacebookProfileList {
            get {
                return ResourceManager.GetString("FacebookProfileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name.
        /// </summary>
        public static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the first name.
        /// </summary>
        public static string FirstNamePlaceHolder {
            get {
                return ResourceManager.GetString("FirstNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a first name.
        /// </summary>
        public static string FirstNameValidation {
            get {
                return ResourceManager.GetString("FirstNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string Forgot {
            get {
                return ResourceManager.GetString("Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a French:.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From camera.
        /// </summary>
        public static string FromCamera {
            get {
                return ResourceManager.GetString("FromCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From gallery.
        /// </summary>
        public static string FromGallery {
            get {
                return ResourceManager.GetString("FromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fuchsia.
        /// </summary>
        public static string Fuchsia {
            get {
                return ResourceManager.GetString("Fuchsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a German:.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GINI:.
        /// </summary>
        public static string GINI {
            get {
                return ResourceManager.GetString("GINI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This number has whatsapp..
        /// </summary>
        public static string HaveWhats {
            get {
                return ResourceManager.GetString("HaveWhats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How do I read another TAG?.
        /// </summary>
        public static string HelpLabel {
            get {
                return ResourceManager.GetString("HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hold your Phone near the sticker..
        /// </summary>
        public static string HoldYourPhone {
            get {
                return ResourceManager.GetString("HoldYourPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Italian:.
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Japanese:.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must add a valid side..
        /// </summary>
        public static string LadaValidation {
            get {
                return ResourceManager.GetString("LadaValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        public static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the last name....
        /// </summary>
        public static string LastNamePlaceHolder {
            get {
                return ResourceManager.GetString("LastNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a last name.
        /// </summary>
        public static string LastNameValidation {
            get {
                return ResourceManager.GetString("LastNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Light blue.
        /// </summary>
        public static string LightBlue {
            get {
                return ResourceManager.GetString("LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lilac.
        /// </summary>
        public static string Lilac {
            get {
                return ResourceManager.GetString("Lilac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile URL.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a url.
        /// </summary>
        public static string LinkValidation {
            get {
                return ResourceManager.GetString("LinkValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location:.
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manhattan, Nueva York, EE. UU..
        /// </summary>
        public static string LocationPlaceHolder {
            get {
                return ResourceManager.GetString("LocationPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email or password incorrect..
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string LoginSession {
            get {
                return ResourceManager.GetString("LoginSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My accounts in.
        /// </summary>
        public static string MyAccounts {
            get {
                return ResourceManager.GetString("MyAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Languages.
        /// </summary>
        public static string MyLanguages {
            get {
                return ResourceManager.GetString("MyLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profiles.
        /// </summary>
        public static string MyProfiles {
            get {
                return ResourceManager.GetString("MyProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My QR.
        /// </summary>
        public static string MyQR {
            get {
                return ResourceManager.GetString("MyQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile name.
        /// </summary>
        public static string NameProfile {
            get {
                return ResourceManager.GetString("NameProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a name.
        /// </summary>
        public static string NameValidation {
            get {
                return ResourceManager.GetString("NameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Native Name:.
        /// </summary>
        public static string NativeName {
            get {
                return ResourceManager.GetString("NativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Network added to the box .
        /// </summary>
        public static string NetworkAdded {
            get {
                return ResourceManager.GetString("NetworkAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Networks list.
        /// </summary>
        public static string NetworksList {
            get {
                return ResourceManager.GetString("NetworksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Box.
        /// </summary>
        public static string NewBox {
            get {
                return ResourceManager.GetString("NewBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the new password....
        /// </summary>
        public static string NewPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("NewPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Profile.
        /// </summary>
        public static string NewProfile {
            get {
                return ResourceManager.GetString("NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string NickName {
            get {
                return ResourceManager.GetString("NickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string NickNamePH {
            get {
                return ResourceManager.GetString("NickNamePH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Business, Personal, Friends..
        /// </summary>
        public static string NProfilePlaceH {
            get {
                return ResourceManager.GetString("NProfilePlaceH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cell number.
        /// </summary>
        public static string NumberPhone {
            get {
                return ResourceManager.GetString("NumberPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a phone number..
        /// </summary>
        public static string NumberValidation {
            get {
                return ResourceManager.GetString("NumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numeric Code:.
        /// </summary>
        public static string NumericCode {
            get {
                return ResourceManager.GetString("NumericCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occupation:.
        /// </summary>
        public static string OccupationLabel {
            get {
                return ResourceManager.GetString("OccupationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Information Technology Engineer..
        /// </summary>
        public static string OccupationPlaceHolder {
            get {
                return ResourceManager.GetString("OccupationPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The current password is incorrect.
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your password....
        /// </summary>
        public static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a password.
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must have at least six (6) characters.
        /// </summary>
        public static string PasswordValidation2 {
            get {
                return ResourceManager.GetString("PasswordValidation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persian:.
        /// </summary>
        public static string Persian {
            get {
                return ResourceManager.GetString("Persian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone.
        /// </summary>
        public static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the phone..
        /// </summary>
        public static string PhonePlaceHolder {
            get {
                return ResourceManager.GetString("PhonePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone profile list.
        /// </summary>
        public static string PhoneProfileList {
            get {
                return ResourceManager.GetString("PhoneProfileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a phone number.
        /// </summary>
        public static string PhoneValidation {
            get {
                return ResourceManager.GetString("PhoneValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The phone number must contain 10 digits.
        /// </summary>
        public static string PhoneValidation2 {
            get {
                return ResourceManager.GetString("PhoneValidation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pink.
        /// </summary>
        public static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Population:.
        /// </summary>
        public static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portuguese:.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile details.
        /// </summary>
        public static string ProfileDetails {
            get {
                return ResourceManager.GetString("ProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your user was created by a social network, to make a change you must make it from that same social network.
        /// </summary>
        public static string ProfileELabel {
            get {
                return ResourceManager.GetString("ProfileELabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mynfo Profile.
        /// </summary>
        public static string ProfileMynfo {
            get {
                return ResourceManager.GetString("ProfileMynfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile name.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have not created any profile of this type yet.
        /// </summary>
        public static string ProfileNull {
            get {
                return ResourceManager.GetString("ProfileNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone profile.
        /// </summary>
        public static string ProfilePhone {
            get {
                return ResourceManager.GetString("ProfilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My active profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Purple.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Push.
        /// </summary>
        public static string Push {
            get {
                return ResourceManager.GetString("Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your email..
        /// </summary>
        public static string PutEmail {
            get {
                return ResourceManager.GetString("PutEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QR code.
        /// </summary>
        public static string QR {
            get {
                return ResourceManager.GetString("QR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This QR code will allow you to share your default box in any browser..
        /// </summary>
        public static string QRForWhat {
            get {
                return ResourceManager.GetString("QRForWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scan a QR code from Mynfo..
        /// </summary>
        public static string QRMynfo {
            get {
                return ResourceManager.GetString("QRMynfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready to Scan..
        /// </summary>
        public static string ReadyToScan {
            get {
                return ResourceManager.GetString("ReadyToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connections.
        /// </summary>
        public static string ReceivedBoxes {
            get {
                return ResourceManager.GetString("ReceivedBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Region:.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register New User.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember me in this device.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search..
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a color.
        /// </summary>
        public static string SelectColor {
            get {
                return ResourceManager.GetString("SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We will send an email so you can log in..
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Something was wrong, please try again later.
        /// </summary>
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Where do you want to take the image?.
        /// </summary>
        public static string SourceImageQuestion {
            get {
                return ResourceManager.GetString("SourceImageQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish:.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statics.
        /// </summary>
        public static string Statics {
            get {
                return ResourceManager.GetString("Statics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subregion:.
        /// </summary>
        public static string Subregion {
            get {
                return ResourceManager.GetString("Subregion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Make sure you have your TAG at hand..
        /// </summary>
        public static string SureTAG {
            get {
                return ResourceManager.GetString("SureTAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configure Tag.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you don&apos;t have it yet, buy it at.
        /// </summary>
        public static string TakeinStore {
            get {
                return ResourceManager.GetString("TakeinStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Translations.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user was created, now you can login with this email and password.
        /// </summary>
        public static string UserRegisteredMessage {
            get {
                return ResourceManager.GetString("UserRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connections: .
        /// </summary>
        public static string ViewsLabel {
            get {
                return ResourceManager.GetString("ViewsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List of Whatsapp profiles.
        /// </summary>
        public static string WhatsappProfileList {
            get {
                return ResourceManager.GetString("WhatsappProfileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It already exists an account with that email, try again with a different one.
        /// </summary>
        public static string WrongEmail {
            get {
                return ResourceManager.GetString("WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Golden.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
